"""added card print date

Revision ID: 7e5c3cff1af8
Revises: 
Create Date: 2025-06-04 16:56:28.126856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e5c3cff1af8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_token', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('artist', sa.String(length=64), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('card_print_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('song_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    # ### end Alembic commands ###
